FROM node:16-alpine
WORKDIR /app
COPY /src/prepareDatabase.mjs .
COPY prisma ./prisma
COPY .env.docker .
COPY .env.docker .env
RUN npm install prisma bcrypt
RUN npx prisma generate
CMD [ "node", "prepareDatabase.mjs" ]
