version: '3.9'

services:
  mongo1:
    container_name: mongo1
    image: mongo:5.0.9
    volumes:
      - ./scripts/rs-init.sh:/scripts/rs-init.sh
    networks:
      - mongo-network
    ports:
      - 27017:27017
    depends_on:
      - mongo2
      - mongo3
    links:
      - mongo2
      - mongo3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]


  mongo2:
    container_name: mongo2
    image: mongo:5.0.9
    networks:
      - mongo-network
    ports:
      - 27018:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  mongo3:
    container_name: mongo3
    image: mongo:5.0.9
    networks:
      - mongo-network
    ports:
      - 27019:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  nextjs:
    container_name: nextjs
    image: abdimehdi/havas:latest
    networks:
      - mongo-network
    ports:
      - 3000:3000
    depends_on:
      - mongo1
    env_file:
      - .env.docker
  mqttBroker:
    container_name: mqttBroker
    image: hivemq/hivemq-ce
    ports:
      - 1883:1883
      - 8000:8000
    restart: always


networks:
  mongo-network:
    driver: bridge