import { ComponentMeta, ComponentStory } from '@storybook/react';

import React from 'react';
import StoriesDecorator from '../../StoriesDecorator';
import WorkflowStagesModal from './WorkflowStagesModal';

// More on default export: https://storybook.js.org/docs/react/writing-stories/introduction#default-export
export default {
  title: 'Components/ WorkflowStagesModal',
  component: WorkflowStagesModal,
  decorators: [
    (Story) => (
      <StoriesDecorator>
        <Story />
      </StoriesDecorator>
    ),
  ],
} as ComponentMeta<typeof WorkflowStagesModal>;

// More on component templates: https://storybook.js.org/docs/react/writing-stories/introduction#using-args
const Template: ComponentStory<typeof WorkflowStagesModal> = (args: any) => (
  <WorkflowStagesModal {...args} />
);

export const Main = Template.bind({});
// More on args: https://storybook.js.org/docs/react/writing-stories/args
Main.args = {
  data: {
    id: '6',
    instanceOfProcessId:2,
    nextStageName: '',
    dateCreated: '1659685654011',
    dateModified: '1659685680668',
    passedStages: [
      {
        stageID: "1",
        stageName: 'ثبت خروج کپسول از بیمارستان',
        submittedByUser: {
          id: '0520926458',
          firstNameAndLastName: 'مهدی عبدی',
        },
        havaleh: {
          id: 'xcvcxcv',
          date: '1659685627933',
          deliverer: null,
          transportationName: 'ee',
          transportationTelephone: 'xcvxcv',
          transportationTelephone2: '',
          description: null,
          receivingDescription: null,
          corporation: {
            id: 'dff7b479-f3a5-45db-a022-cb567108666d',
            name: 'اداری',
          },
          assets: {
            oxygen_50l_factory: 3,
            bihoshi_50l_factory: null,
            shaft_50l_factory: null,
            controlValve_50l_factory: null,
            co2_50l_factory: null,
            argon_50l_factory: null,
            azete_50l_factory: null,
            dryAir_50l_factory: null,
            entonox_50l_factory: null,
            acetylene_50l_factory: null,
            lpg_50l_factory: null,
            oxygen_50l_customer: null,
            bihoshi_50l_customer: null,
            shaft_50l_customer: null,
            controlValve_50l_customer: null,
            co2_50l_customer: null,
            argon_50l_customer: null,
            azete_50l_customer: null,
            dryAir_50l_customer: null,
            entonox_50l_customer: null,
            acetylene_50l_customer: null,
            lpg_50l_customer: null,
            oxygen_40l_factory: null,
            bihoshi_40l_factory: 3,
            shaft_40l_factory: null,
            controlValve_40l_factory: null,
            co2_40l_factory: null,
            argon_40l_factory: null,
            azete_40l_factory: null,
            dryAir_40l_factory: null,
            entonox_40l_factory: null,
            acetylene_40l_factory: null,
            lpg_40l_factory: null,
            oxygen_40l_customer: null,
            bihoshi_40l_customer: null,
            shaft_40l_customer: null,
            controlValve_40l_customer: null,
            co2_40l_customer: null,
            argon_40l_customer: null,
            azete_40l_customer: null,
            dryAir_40l_customer: null,
            entonox_40l_customer: null,
            acetylene_40l_customer: null,
            lpg_40l_customer: null,
            oxygen_50l: 3,
            bihoshi_50l: null,
            shaft_50l: null,
            controlValve_50l: null,
            co2_50l: null,
            argon_50l: null,
            azete_50l: null,
            dryAir_50l: null,
            entonox_50l: null,
            acetylene_50l: null,
            lpg_50l: null,
            oxygen_40l: null,
            bihoshi_40l: 3,
            shaft_40l: null,
            controlValve_40l: null,
            co2_40l: null,
            argon_40l: null,
            azete_40l: null,
            dryAir_40l: null,
            entonox_40l: null,
            acetylene_40l: null,
            lpg_40l: null,
          },
        },
      },
      {
        stageID: "2",
        stageName: 'قبول درخواست توسط مدیریت',
        submittedByUser: {
          id: '0520926458',
          firstNameAndLastName: 'مهدی عبدی',
        },
        havaleh: null,
      },
      {
        stageID: "3",
        stageName: 'RFID ثبت خروج کپسول از انبار توسط',
        submittedByUser: {
          id: '0520926458',
          firstNameAndLastName: 'مهدی عبدی',
        },
        havaleh: {
          id: null,
          date: null,
          deliverer: null,
          transportationName: null,
          transportationTelephone: null,
          transportationTelephone2: null,
          description: null,
          receivingDescription: null,
          corporation: null,
          assets: {
            oxygen_50l_factory: null,
            bihoshi_50l_factory: null,
            shaft_50l_factory: null,
            controlValve_50l_factory: null,
            co2_50l_factory: null,
            argon_50l_factory: null,
            azete_50l_factory: null,
            dryAir_50l_factory: null,
            entonox_50l_factory: null,
            acetylene_50l_factory: null,
            lpg_50l_factory: null,
            oxygen_50l_customer: null,
            bihoshi_50l_customer: null,
            shaft_50l_customer: null,
            controlValve_50l_customer: null,
            co2_50l_customer: null,
            argon_50l_customer: null,
            azete_50l_customer: null,
            dryAir_50l_customer: null,
            entonox_50l_customer: null,
            acetylene_50l_customer: null,
            lpg_50l_customer: null,
            oxygen_40l_factory: null,
            bihoshi_40l_factory: null,
            shaft_40l_factory: null,
            controlValve_40l_factory: null,
            co2_40l_factory: null,
            argon_40l_factory: null,
            azete_40l_factory: null,
            dryAir_40l_factory: null,
            entonox_40l_factory: null,
            acetylene_40l_factory: null,
            lpg_40l_factory: null,
            oxygen_40l_customer: null,
            bihoshi_40l_customer: null,
            shaft_40l_customer: null,
            controlValve_40l_customer: null,
            co2_40l_customer: null,
            argon_40l_customer: null,
            azete_40l_customer: null,
            dryAir_40l_customer: null,
            entonox_40l_customer: null,
            acetylene_40l_customer: null,
            lpg_40l_customer: null,
            oxygen_50l: null,
            bihoshi_50l: null,
            shaft_50l: null,
            controlValve_50l: null,
            co2_50l: null,
            argon_50l: null,
            azete_50l: null,
            dryAir_50l: null,
            entonox_50l: null,
            acetylene_50l: null,
            lpg_50l: null,
            oxygen_40l: null,
            bihoshi_40l: null,
            shaft_40l: null,
            controlValve_40l: null,
            co2_40l: null,
            argon_40l: null,
            azete_40l: null,
            dryAir_40l: null,
            entonox_40l: null,
            acetylene_40l: null,
            lpg_40l: null,
          },
        },
      },
      {
        stageID: "4",
        stageName: 'تایید تحویل به شرکت',
        submittedByUser: {
          id: '0520926458',
          firstNameAndLastName: 'شایان عبدی',
        },
        havaleh: {
          id: 'xcvcxcvedited',
          date: '1659685627933',
          transportationName: 'ee',
          transportationTelephone: 'xcvxcv',
          transportationTelephone2: '',
          description: null,
          receivingDescription: 'توضیحات ارسال عزیزم',
          assets: {
            oxygen_50l: 6,
            bihoshi_40l: 6,
          },
        },
      },
    ],
  },
};
